language: generic
sudo: required

# specified the services
services:
  - docker

# do this before install eg build an image with dockerfile
before_install:
  - docker build -t lekan123/docker-react -f Dockerfile.dev .

# command to run test
script:
  - docker run -e CI=true lekan123/docker-react npm run test