language: generic
sudo: required

# specified the services
services:
  - docker

# do this before install eg build an image with dockerfile
before_install:
  - docker build -t lekan123/docker-react -f Dockerfile.dev .

# command to run test
script:
  - docker run -e CI=true lekan123/docker-react npm run test

# deployment provider setup
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-100853778864"
  bucket_path: "docker-react"
  on:
    branch: master

  # AWS USERS IAM STORED IN TRAVIS CI ENV
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY